spring.datasource.url=jdbc:postgresql://battlepass_db:5432/battlepass
spring.datasource.username=battlepass
spring.datasource.password=battlepass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
